
server:
  port: 8000

spring:
  application:
    name: gateway-service

  main:
    web-application-type: reactive

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
