name: Docker Hub Push

on:
  push:
    branches:
      - '**/dev'
      - '!web/dev'
      - '!android/dev'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          # Extract branch name from GITHUB_REF
          BRANCH_NAME=$(echo $GITHUB_REF | awk -F'/' '{print $3}')
  
          if [ -n "$BRANCH_NAME" ]; then
            DOCKERFILE_DIR="src/$BRANCH_NAME-service"
          else
            echo "Failed to extract branch name from GITHUB_REF."
            exit 1
          fi
  
          cd $DOCKERFILE_DIR
          docker build -t $DOCKER_USERNAME/$BRANCH_NAME-service:latest .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push $DOCKER_USERNAME/$BRANCH_NAME-service:latest
